var books = [
  { name: "التكوين", ref: "ONAV-01-GEN-001.html" },
  { name: "الخروج", ref: "ONAV-02-EXO-001.html" },
  { name: "اللاويين", ref: "ONAV-03-LEV-001.html" },
  { name: "العدد", ref: "ONAV-04-NUM-001.html" },
  { name: "التثنية", ref: "ONAV-05-DEU-001.html" },
  { name: "يشوع", ref: "ONAV-06-JOS-001.html" },
  { name: "القضاة", ref: "ONAV-07-JDG-001.html" },
  { name: "راعوث", ref: "ONAV-08-RUT-001.html" },
  { name: "صموئيل الأول", ref: "ONAV-09-1SA-001.html" },
  { name: "صموئيل الثاني", ref: "ONAV-10-2SA-001.html" },
  { name: "ملوك الأول", ref: "ONAV-11-1KI-001.html" },
  { name: "ملوك الثاني", ref: "ONAV-12-2KI-001.html" },
  { name: "أخبار الأيام الأول", ref: "ONAV-13-1CH-001.html" },
  { name: "أخبار الأيام الثاني", ref: "ONAV-14-2CH-001.html" },
  { name: "عزرا", ref: "ONAV-15-EZR-001.html" },
  { name: "نحميا", ref: "ONAV-16-NEH-001.html" },
  { name: "أستير", ref: "ONAV-17-EST-001.html" },
  { name: "أيوب", ref: "ONAV-18-JOB-001.html" },
  { name: "مزمور", ref: "ONAV-19-PSA-001.html" },
  { name: "الأمثال", ref: "ONAV-20-PRO-001.html" },
  { name: "الجامعة", ref: "ONAV-21-ECC-001.html" },
  { name: "نشيد الأنشاد", ref: "ONAV-22-SNG-001.html" },
  { name: "إشعياء", ref: "ONAV-23-ISA-001.html" },
  { name: "إرميا", ref: "ONAV-24-JER-001.html" },
  { name: "مراثي إرميا", ref: "ONAV-25-LAM-001.html" },
  { name: "حزقيال", ref: "ONAV-26-EZK-001.html" },
  { name: "دانيال", ref: "ONAV-27-DAN-001.html" },
  { name: "هوشع", ref: "ONAV-28-HOS-001.html" },
  { name: "يوئيل", ref: "ONAV-29-JOL-001.html" },
  { name: "عاموس", ref: "ONAV-30-AMO-001.html" },
  { name: "عوبديا", ref: "ONAV-31-OBA-001.html" },
  { name: "يونان", ref: "ONAV-32-JON-001.html" },
  { name: "ميخا", ref: "ONAV-33-MIC-001.html" },
  { name: "ناحوم", ref: "ONAV-34-NAM-001.html" },
  { name: "حبقوق", ref: "ONAV-35-HAB-001.html" },
  { name: "صفنيا", ref: "ONAV-36-ZEP-001.html" },
  { name: "حجي", ref: "ONAV-37-HAG-001.html" },
  { name: "زكريا", ref: "ONAV-38-ZEC-001.html" },
  { name: "ملاخي", ref: "ONAV-39-MAL-001.html" },
  { name: "إنجيل متى", ref: "ONAV-40-MAT-001.html" },
  { name: "إنجيل مرقس", ref: "ONAV-41-MRK-001.html" },
  { name: "إنجيل لوقا", ref: "ONAV-42-LUK-001.html" },
  { name: "إنجيل يوحنا", ref: "ONAV-43-JHN-001.html" },
  { name: "أعمال", ref: "ONAV-44-ACT-001.html" },
  { name: "روما", ref: "ONAV-45-ROM-001.html" },
  { name: "كورنثوس الأولى", ref: "ONAV-46-1CO-001.html" },
  { name: "كورنثوس الثانية", ref: "ONAV-47-2CO-001.html" },
  { name: "غلاطية", ref: "ONAV-48-GAL-001.html" },
  { name: "أفسس", ref: "ONAV-49-EPH-001.html" },
  { name: "فيلبي", ref: "ONAV-50-PHP-001.html" },
  { name: "كولوسي", ref: "ONAV-51-COL-001.html" },
  { name: "تسالونيكي الأولى", ref: "ONAV-52-1TH-001.html" },
  { name: "تسالونيكي الثانية", ref: "ONAV-53-2TH-001.html" },
  { name: "تيموثاوس الأولى", ref: "ONAV-54-1TI-001.html" },
  { name: "تيموثاوس الثانية", ref: "ONAV-55-2TI-001.html" },
  { name: "تيطس", ref: "ONAV-56-TIT-001.html" },
  { name: "فليمون", ref: "ONAV-57-PHM-001.html" },
  { name: "العبرانيين", ref: "ONAV-58-HEB-001.html" },
  { name: "يعقوب", ref: "ONAV-59-JAS-001.html" },
  { name: "بطرس الأولى", ref: "ONAV-60-1PE-001.html" },
  { name: "بطرس الثانية", ref: "ONAV-61-2PE-001.html" },
  { name: "يوحنا الأولى", ref: "ONAV-62-1JN-001.html" },
  { name: "يوحنا الثانية", ref: "ONAV-63-2JN-001.html" },
  { name: "يوحنا الثالثة", ref: "ONAV-64-3JN-001.html" },
  { name: "يهوذا", ref: "ONAV-65-JUD-001.html" },
  { name: "رؤيا يوحنا", ref: "ONAV-66-REV-001.html" },
];
